services:
  - type: web
    name: smartgarbage
    runtime: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: RENDER
        value: "true"
      - key: PYTHON_VERSION
        value: "3.12"
      - key: SECRET_KEY
        sync: false
      - key: RAZOR_PUBLIC_KEY
        sync: false
      - key: SENTRY_DSN
        sync: false
      - key: CLOUDINARY_URL
        sync: false
      - key: IOT_TELEMETRY_SECRET
        sync: false
