services:
  - type: web
    name: smartgarbage
    runtime: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: RENDER
        value: "true"
      - key: PYTHON_VERSION
        value: "3.12"
    disks:
      - name: data
        mountPoint: /data
        sizeGB: 1
