"""baseline: current full schema (roles, IoT, billing, segregation, worker safety, indexes)

Revision ID: 1325887fe8ed
Revises: 
Create Date: 2026-07-19 12:37:27.730636

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1325887fe8ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('illegal_dump_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scrubbed_photo', sa.String(length=200), nullable=True),
    sa.Column('ward', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_illegal_dump_report_timestamp'), 'illegal_dump_report', ['timestamp'], unique=False)
    op.create_index(op.f('ix_illegal_dump_report_ward'), 'illegal_dump_report', ['ward'], unique=False)
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('ward', sa.String(length=100), nullable=False),
    sa.Column('day', sa.String(length=20), nullable=True),
    sa.Column('time_slot', sa.String(length=50), nullable=True),
    sa.Column('vehicle_id', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('smart_bin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hardware_id', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('battery_level', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('methane', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('ward', sa.String(length=100), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('overflow_eta_hours', sa.Float(), nullable=True),
    sa.Column('waste_stream', sa.String(length=20), nullable=True),
    sa.Column('sensor_fault', sa.Boolean(), nullable=False),
    sa.Column('decomposition_started_at', sa.DateTime(), nullable=True),
    sa.Column('precompaction_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_compacted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hardware_id')
    )
    op.create_index(op.f('ix_smart_bin_last_updated'), 'smart_bin', ['last_updated'], unique=False)
    op.create_index(op.f('ix_smart_bin_ward'), 'smart_bin', ['ward'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('green_points', sa.Integer(), nullable=False),
    sa.Column('otp', sa.String(length=10), nullable=True),
    sa.Column('otp_expiry', sa.DateTime(), nullable=True),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('segregation_streak', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=100), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_table('bwg_declaration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_name', sa.String(length=200), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('composting_kg', sa.Float(), nullable=False),
    sa.Column('recyclable_kg', sa.Float(), nullable=False),
    sa.Column('landfill_kg', sa.Float(), nullable=False),
    sa.Column('request_bulk_pickup', sa.Boolean(), nullable=False),
    sa.Column('pickup_status', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complaint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('ward', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('photo', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.String(length=50), nullable=True),
    sa.Column('longitude', sa.String(length=50), nullable=True),
    sa.Column('report_time', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_created_at'), 'complaint', ['created_at'], unique=False)
    op.create_index(op.f('ix_complaint_user_id'), 'complaint', ['user_id'], unique=False)
    op.create_table('firmware_release',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_bins', sa.Text(), nullable=True),
    sa.Column('pushed_at', sa.DateTime(), nullable=True),
    sa.Column('push_status', sa.String(length=20), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bin_id', sa.Integer(), nullable=True),
    sa.Column('incident_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bin_id'], ['smart_bin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payt_invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=50), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('bin_pickups', sa.Integer(), nullable=False),
    sa.Column('segregation_kg', sa.Float(), nullable=False),
    sa.Column('landfill_kg', sa.Float(), nullable=False),
    sa.Column('compliance_score', sa.Float(), nullable=False),
    sa.Column('penalty_multiplier', sa.Float(), nullable=False),
    sa.Column('base_amount_rs', sa.Float(), nullable=False),
    sa.Column('amount_rs', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor_health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bin_id', sa.Integer(), nullable=False),
    sa.Column('battery_voltage', sa.Float(), nullable=False),
    sa.Column('calibration_drift', sa.Float(), nullable=False),
    sa.Column('last_ping', sa.DateTime(), nullable=True),
    sa.Column('fault_flag', sa.Boolean(), nullable=False),
    sa.Column('fault_reason', sa.String(length=200), nullable=True),
    sa.Column('maintenance_scheduled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bin_id'], ['smart_bin.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bin_id')
    )
    op.create_table('waste_declaration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('wet_kg', sa.Float(), nullable=False),
    sa.Column('dry_kg', sa.Float(), nullable=False),
    sa.Column('sanitary_kg', sa.Float(), nullable=False),
    sa.Column('hazardous_kg', sa.Float(), nullable=False),
    sa.Column('ward', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waste_declaration_user_id'), 'waste_declaration', ['user_id'], unique=False)
    op.create_table('worker_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.String(length=20), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('performance_rating', sa.Float(), nullable=False),
    sa.Column('sector_polygon', sa.Text(), nullable=True),
    sa.Column('current_lat', sa.Float(), nullable=True),
    sa.Column('current_lon', sa.Float(), nullable=True),
    sa.Column('geofence_violation', sa.Boolean(), nullable=False),
    sa.Column('ppe_compliance', sa.Boolean(), nullable=False),
    sa.Column('training_completed', sa.Boolean(), nullable=False),
    sa.Column('insurance_enrolled', sa.Boolean(), nullable=False),
    sa.Column('insurance_policy_no', sa.String(length=50), nullable=True),
    sa.Column('last_training_date', sa.DateTime(), nullable=True),
    sa.Column('last_medical_checkup', sa.DateTime(), nullable=True),
    sa.Column('is_informal_picker', sa.Boolean(), nullable=False),
    sa.Column('picker_area', sa.String(length=100), nullable=True),
    sa.Column('picker_id_card', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('offload_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('dump_yard_id', sa.String(length=50), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('vehicle_id', sa.String(length=20), nullable=True),
    sa.Column('impurity_flagged', sa.Boolean(), nullable=False),
    sa.Column('impurity_detail', sa.String(length=200), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['worker_id'], ['worker_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offload_log')
    op.drop_table('worker_profile')
    op.drop_index(op.f('ix_waste_declaration_user_id'), table_name='waste_declaration')
    op.drop_table('waste_declaration')
    op.drop_table('sensor_health')
    op.drop_table('payt_invoice')
    op.drop_table('notification')
    op.drop_table('incident_log')
    op.drop_table('firmware_release')
    op.drop_index(op.f('ix_complaint_user_id'), table_name='complaint')
    op.drop_index(op.f('ix_complaint_created_at'), table_name='complaint')
    op.drop_table('complaint')
    op.drop_table('bwg_declaration')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('user')
    op.drop_index(op.f('ix_smart_bin_ward'), table_name='smart_bin')
    op.drop_index(op.f('ix_smart_bin_last_updated'), table_name='smart_bin')
    op.drop_table('smart_bin')
    op.drop_table('schedule')
    op.drop_index(op.f('ix_illegal_dump_report_ward'), table_name='illegal_dump_report')
    op.drop_index(op.f('ix_illegal_dump_report_timestamp'), table_name='illegal_dump_report')
    op.drop_table('illegal_dump_report')
    # ### end Alembic commands ###
