"""add_device_model_for_per_bin_iot_auth

Revision ID: 66d344fab3f9
Revises: f3a4b5c6d7e8
Create Date: 2026-08-03 10:37:29.921682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66d344fab3f9'
down_revision = 'f3a4b5c6d7e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hardware_id', sa.String(length=50), nullable=False),
    sa.Column('api_key_hash', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_hardware_id'), ['hardware_id'], unique=True)

    # NOTE: uq_dispatch_bin_assigned was ALREADY created by c3d4e5f6a7b8 (the
    # merge revision that added dispatch_assignment). Re-creating it here broke
    # fresh full upgrades ("index already exists"); the index is intentionally
    # left untouched by this revision.

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_hardware_id'))

    op.drop_table('device')
    # ### end Alembic commands ###
