"""Add segregation_streak to User and Notification model

Revision ID: 6cdf00e23730
Revises: auto
Create Date: 2026-07-18 22:29:00.787942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cdf00e23730'
down_revision = 'auto'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('segregation_streak', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'segregation_streak')
    # ### end Alembic commands ###
