"""add offline delivery table (PWA queue replay health)

Revision ID: a1b2c3d4e5f6
Revises: c9d8e7f6a5b4
Create Date: 2026-08-01 09:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'c9d8e7f6a5b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offline_delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=True),
    sa.Column('illegal_report_id', sa.Integer(), nullable=True),
    sa.Column('ward', sa.String(length=100), nullable=True),
    sa.Column('has_photo', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaint.id'], ),
    sa.ForeignKeyConstraint(['illegal_report_id'], ['illegal_dump_report.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offline_delivery_delivered_at'), 'offline_delivery', ['delivered_at'], unique=False)
    op.create_index(op.f('ix_offline_delivery_ward'), 'offline_delivery', ['ward'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offline_delivery_ward'), table_name='offline_delivery')
    op.drop_index(op.f('ix_offline_delivery_delivered_at'), table_name='offline_delivery')
    op.drop_table('offline_delivery')
    # ### end Alembic commands ###
