"""Add worker safety fields and PAYT compliance penalty

Revision ID: auto
Revises: f0a42f90a44b
Create Date: 2026-07-18 21:57:02.934159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'auto'
down_revision = 'f0a42f90a44b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payt_invoice', sa.Column('segregation_kg', sa.Float(), nullable=False))
    op.add_column('payt_invoice', sa.Column('landfill_kg', sa.Float(), nullable=False))
    op.add_column('payt_invoice', sa.Column('compliance_score', sa.Float(), nullable=False))
    op.add_column('payt_invoice', sa.Column('penalty_multiplier', sa.Float(), nullable=False))
    op.add_column('payt_invoice', sa.Column('base_amount_rs', sa.Float(), nullable=False))
    op.add_column('worker_profile', sa.Column('ppe_compliance', sa.Boolean(), nullable=False))
    op.add_column('worker_profile', sa.Column('training_completed', sa.Boolean(), nullable=False))
    op.add_column('worker_profile', sa.Column('insurance_enrolled', sa.Boolean(), nullable=False))
    op.add_column('worker_profile', sa.Column('insurance_policy_no', sa.String(length=50), nullable=True))
    op.add_column('worker_profile', sa.Column('last_training_date', sa.DateTime(), nullable=True))
    op.add_column('worker_profile', sa.Column('last_medical_checkup', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('worker_profile', 'last_medical_checkup')
    op.drop_column('worker_profile', 'last_training_date')
    op.drop_column('worker_profile', 'insurance_policy_no')
    op.drop_column('worker_profile', 'insurance_enrolled')
    op.drop_column('worker_profile', 'training_completed')
    op.drop_column('worker_profile', 'ppe_compliance')
    op.drop_column('payt_invoice', 'base_amount_rs')
    op.drop_column('payt_invoice', 'penalty_multiplier')
    op.drop_column('payt_invoice', 'compliance_score')
    op.drop_column('payt_invoice', 'landfill_kg')
    op.drop_column('payt_invoice', 'segregation_kg')
    # ### end Alembic commands ###
