"""add razorpay_order_id to payt invoice for server-side order tracking

Revision ID: b1c2d3e4f5a6
Revises: d4a5b6c7d8e9
Create Date: 2026-08-01 10:30:00.000000

The order id is created server-side before the Razorpay Checkout opens so the
capture webhook can map an order back to its invoice without trusting any
client-supplied reference.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c2d3e4f5a6'
down_revision = 'd4a5b6c7d8e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payt_invoice', sa.Column('razorpay_order_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_payt_invoice_razorpay_order_id'), 'payt_invoice', ['razorpay_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payt_invoice_razorpay_order_id'), table_name='payt_invoice')
    op.drop_column('payt_invoice', 'razorpay_order_id')
    # ### end Alembic commands ###
