"""add live telemetry history table (per-ping level snapshots)

Revision ID: b2c3d4e5f6a7
Revises: a1b2c3d4e5f6
Create Date: 2026-08-01 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2c3d4e5f6a7'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bin_telemetry_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bin_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('methane', sa.Float(), nullable=True),
    sa.Column('battery_level', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bin_id'], ['smart_bin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bin_telemetry_log_bin_timestamp'), 'bin_telemetry_log', ['bin_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_bin_telemetry_log_timestamp'), 'bin_telemetry_log', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bin_telemetry_log_timestamp'), table_name='bin_telemetry_log')
    op.drop_index(op.f('ix_bin_telemetry_log_bin_timestamp'), table_name='bin_telemetry_log')
    op.drop_table('bin_telemetry_log')
    # ### end Alembic commands ###
