"""add payt payment confirmation fields

Revision ID: e11a6badfb75
Revises: 1325887fe8ed
Create Date: 2026-07-20 08:01:02.732053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e11a6badfb75'
down_revision = '1325887fe8ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payt_invoice', sa.Column('paid_at', sa.DateTime(), nullable=True))
    op.add_column('payt_invoice', sa.Column('transaction_ref', sa.String(length=120), nullable=True))
    op.add_column('payt_invoice', sa.Column('payment_method', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payt_invoice', 'payment_method')
    op.drop_column('payt_invoice', 'transaction_ref')
    op.drop_column('payt_invoice', 'paid_at')
    # ### end Alembic commands ###
