Add-Type -AssemblyName System.Speech
$v = New-Object System.Speech.Synthesis.SpeechSynthesizer
$v.SelectVoice('Microsoft Zira Desktop')
$v.Rate = 0
$v.SetOutputToWaveFile('C:/Users/chand/SmartGarbage/report/video/_video_live/narr00.wav')
$v.Speak('Welcome to SmartGarbage Chintalavalasa - the community waste management portal for the five wards of Chintalavalasa Gram Panchayat. Let me walk you through the live website, feature by feature.')
$v.SetOutputToWaveFile($null)
$v.SetOutputToWaveFile('C:/Users/chand/SmartGarbage/report/video/_video_live/narr01.wav')
$v.Speak('This is the public homepage. Notice the helpline number 1800 119 9111 and the collection schedule quick search right at the top. As we scroll, you can see ward-wise collection days, the transparency statistics, and the community impact numbers - all live from the database.')
$v.SetOutputToWaveFile($null)
$v.SetOutputToWaveFile('C:/Users/chand/SmartGarbage/report/video/_video_live/narr02.wav')
$v.Speak('Every citizen can check their ward''s collection schedule here. Pick a ward - watch as I select Ward 2, Junction - and the portal shows the pickup days, plus a machine learning overflow-risk prediction for the coming days. No phone calls, no guesswork.')
$v.SetOutputToWaveFile($null)
$v.SetOutputToWaveFile('C:/Users/chand/SmartGarbage/report/video/_video_live/narr03.wav')
$v.Speak('Reporting a missed pickup takes under a minute. The form captures your ward, the location with automatic GPS, and a photo as proof. Every submission gets a tracking token, and duplicates within 100 metres or 30 minutes are rejected automatically.')
$v.SetOutputToWaveFile($null)
$v.SetOutputToWaveFile('C:/Users/chand/SmartGarbage/report/video/_video_live/narr04.wav')
$v.Speak('Below every page sits the rescue strip: the WhatsApp fallback card that opens a saved chat, and the free toll-free grievance helpline 1800 119 9111. Citizens without internet are covered by the offline-first PWA.')
$v.SetOutputToWaveFile($null)
$v.SetOutputToWaveFile('C:/Users/chand/SmartGarbage/report/video/_video_live/narr05.wav')
$v.Speak('The ward transparency dashboard is the accountability view: complaint counts by status, resolution times, and the waste-collection statistics for every ward - published openly for residents.')
$v.SetOutputToWaveFile($null)
$v.SetOutputToWaveFile('C:/Users/chand/SmartGarbage/report/video/_video_live/narr06.wav')
$v.Speak('The impact page summarises the community''s environmental and social gains so far, and the contact page lists every way to reach the panchayat team - WhatsApp, the toll-free helpline, email, and a dedicated grievance form for formal complaints.')
$v.SetOutputToWaveFile($null)
$v.SetOutputToWaveFile('C:/Users/chand/SmartGarbage/report/video/_video_live/narr07.wav')
$v.Speak('The About page explains the initiative and the five wards it serves. The FAQ page answers the common questions - what can be recycled, how Green Points work, and how PAYT billing is calculated.')
$v.SetOutputToWaveFile($null)
$v.SetOutputToWaveFile('C:/Users/chand/SmartGarbage/report/video/_video_live/narr08.wav')
$v.Speak('Every complaint gets a tracking token. The tracking page explains how to follow a complaint''s live status - submitted, assigned, or resolved. Registered users additionally get a personal dashboard, email updates, and their Green Points history - here is the secure login page.')
$v.SetOutputToWaveFile($null)
$v.SetOutputToWaveFile('C:/Users/chand/SmartGarbage/report/video/_video_live/narr09.wav')
$v.Speak('SmartGarbage is an installable Progressive Web App. On a phone, the browser offers an install button; after that the app opens full-screen and keeps working without internet - pages are cached and complaints filed offline sync automatically when connectivity returns.')
$v.SetOutputToWaveFile($null)
$v.SetOutputToWaveFile('C:/Users/chand/SmartGarbage/report/video/_video_live/narr10.wav')
$v.Speak('Under the hood: GitHub pushes auto-deploy to Render, PostgreSQL runs on Supabase, Cloudflare serves the edge, and GitHub Actions pings the health endpoint every fifteen minutes. The entire stack is free-tier.')
$v.SetOutputToWaveFile($null)
$v.SetOutputToWaveFile('C:/Users/chand/SmartGarbage/report/video/_video_live/narr11.wav')
$v.Speak('That is SmartGarbage - schedules, complaints, transparency, machine learning dispatch, gamification and billing, all bilingual in English and Telugu, running at zero cost for the panchayat. Thank you.')
$v.SetOutputToWaveFile($null)
