#!/usr/bin/env python3
"""Generate the inlined critical CSS for base.html.

WHY: base.html inlines an above-the-fold stylesheet so first paint does not
wait on the render-blocking bootstrap.min.css (233 KB) / style.css (45 KB)
round-trip. The critical sheet is a REAL subset of the actual rules (not
hand-written equivalents), extracted from the class names used by the
public templates — so it cannot drift from the real design.

WHEN TO RE-RUN: after editing any public template (adding/removing classes),
or after changing rules in style.css / vendor/bootstrap.min.css that affect
the first screen. The generated file is committed to the repo.

    python scripts/build_critical_css.py

Output: app/templates/partials/critical.css. base.html emits it VERBATIM via
the `critical_css()` template global (see app/__init__.py) — it is read as
raw text, NOT {% include %}-ed, because minified CSS can contain "{{" (e.g.
:not(:last-child){...) that Jinja would misparse.

CSP note: style-src already includes 'unsafe-inline' (app/__init__.py), so
the inline block is permitted.

Dev-only dependency for this script: tinycss2 (pip install tinycss2). It is
not a runtime dependency of the application.
"""
from __future__ import annotations

import gzip
import re
import sys
from pathlib import Path

import tinycss2

ROOT = Path(__file__).resolve().parent.parent
TEMPLATES = ROOT / "app" / "templates"
STATIC = ROOT / "app" / "static"
OUT = TEMPLATES / "partials" / "critical.css"

# Public templates whose markup defines the first screen. base.html is the
# shared shell (navbar, footer, consent banner) and is always included.
SOURCE_TEMPLATES = [
    "base.html",
    "index.html",
    "schedule.html",
    "report.html",
    "ward_transparency.html",
    "about.html",
    "privacy_policy.html",
    "register.html",
    "register_picker.html",
    "login.html",
    "track.html",
    "success.html",
]

# Element/global selectors that must always survive extraction even though
# they carry no class token (body defaults, resets, headings, links).
ALWAYS_KEEP = {
    "*", "html", "body", ":root", "h1", "h2", "h3", "h4", "h5", "h6",
    "a", "a:hover",
}

HEADER = (
    "/* AUTO-GENERATED by scripts/build_critical_css.py — do not edit by hand.\n"
    "   Re-run the script after changing public templates or style.css. */\n"
)


def used_classes(markup: str) -> set[str]:
    classes: set[str] = set()
    for m in re.finditer(r'class="([^"]+)"', markup):
        classes.update(m.group(1).split())
    # Classes referenced by Jinja conditionals / dynamic selectors that do not
    # appear literally in class="" (e.g. 'active' appended server-side).
    classes.update({"active"})
    return classes


def split_rules(css: str) -> list[tuple[str | None, str, str]]:
    """Split CSS into (media_header, selector, body) tuples.

    Uses tinycss2 (a real CSS tokenizer) instead of brace counting: Bootstrap's
    minified :root var block is huge and full of strings/data-URIs that naive
    brace matchers corrupt. Rules inside @media keep their media header as a
    SEPARATE field so the emitter can wrap them in a real block — never
    string-splice a selector (a :not(...) paren would be mistaken for the
    media query's close paren).
    """
    out: list[tuple[str | None, str, str]] = []

    def walk(rules, media: str | None) -> None:
        # `rules` is a list of tinycss2 RULE objects (top level from
        # parse_stylesheet(), or re-parsed @media content). Never call
        # parse_rule_list on rule objects — only on raw token tuples.
        for rule in rules:
            if rule.type == "at-rule":
                if rule.at_keyword == "media":
                    inner = tinycss2.parse_rule_list(rule.content, skip_comments=True, skip_whitespace=True)
                    walk(inner, "@media " + tinycss2.serialize(rule.prelude).strip())
                elif rule.at_keyword == "keyframes":
                    out.append((media, "@keyframes " + tinycss2.serialize(rule.prelude).strip(),
                                tinycss2.serialize(rule.content)))
                # Other at-rules (@charset, @font-face, @import, ...) are not
                # needed inside an inline <style> block — dropped.
            elif rule.type == "qualified-rule":
                out.append((media, tinycss2.serialize(rule.prelude).strip(),
                            tinycss2.serialize(rule.content)))

    walk(tinycss2.parse_stylesheet(css, skip_comments=True, skip_whitespace=True), None)
    return out


def selector_mentions_used(selector: str, used: set[str], keep: set[str]) -> bool:
    tokens = set(re.findall(r"\.([A-Za-z0-9_-]+)", selector))
    if tokens & used:
        return True
    # Element/global selectors (body, h1..h6, a, :root, *) must be kept even
    # though they carry no class token — :root defines the CSS custom
    # properties every var() in the kept rules depends on.
    for part in selector.split(","):
        p = part.strip()
        for k in keep:
            if k == "*":
                if p.startswith("*"):
                    return True
            elif p == k or p.startswith(k + ":") or p.startswith(k + "[") or p.startswith(k + " "):
                return True
    return False


def main() -> int:
    markup = "\n".join(
        (TEMPLATES / t).read_text(encoding="utf-8") for t in SOURCE_TEMPLATES
    )
    used = used_classes(markup)

    css = "\n".join([
        (STATIC / "vendor" / "bootstrap.min.css").read_text(encoding="utf-8"),
        (STATIC / "style.css").read_text(encoding="utf-8"),
    ])

    # Emit every rule as "selector{body}", grouping media-scoped rules into a
    # real @media block per header (media header is carried separately, so no
    # paren-splicing bugs are possible). Keyframes are kept whole.
    plain: list[str] = []
    media_groups: dict[str, list[str]] = {}
    seen: set[str] = set()
    for media, selector, body in split_rules(css):
        if not selector.startswith("@keyframes") and not selector_mentions_used(selector, used, ALWAYS_KEEP):
            continue
        rule = selector + "{" + body + "}"
        if rule in seen:
            continue
        seen.add(rule)
        if media:
            media_groups.setdefault(media, []).append(rule)
        else:
            plain.append(rule)

    kept = plain + [
        hdr + "{" + "".join(rules) + "}"
        for hdr, rules in media_groups.items()
    ]

    content = HEADER + "\n".join(kept) + "\n"
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(content, encoding="utf-8")

    raw = len(content.encode())
    gz = len(gzip.compress(content.encode(), 9))
    print(f"used classes: {len(used)}")
    print(f"kept rules:   {len(kept)}")
    print(f"written:      {OUT}")
    print(f"size:         {raw/1024:.1f} KB raw / {gz/1024:.1f} KB gzipped")
    return 0


if __name__ == "__main__":
    sys.exit(main())
